### ISSUE TITLE
core: throw NullPointerException when try to get aggregate from another type

### ISSUE THREAD

**Issue by georgievJon** [clouway/kcqrs#38]
Should be thrown more appropriate exception when try to get aggregate from another type

```
java.lang.NullPointerException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:265)
	at com.clouway.kcqrs.core.SimpleAggregateRepository.buildAggregateFromHistory(SimpleAggregateRepository.kt:120)
	at com.clouway.kcqrs.core.SimpleAggregateRepository.getById(SimpleAggregateRepository.kt:104)
	at com.clouway.kcqrs.core.AuthoredAggregateRepository.getById(AuthoredAggregateRepository.kt:16)
```

**Comment by VasilMitovClouway** [comment]
Possible solution as suggested from @mgenov is that the aggregate type could be added to the key of the aggregate snapshot which currently is of kind 
```Kotlin
"EventSnapshot"
```
But this solution would only fix the problem partially. If we go with this solution we would do something like 
```Kotlin
//SimpleAggregateRepository

    override fun <T : AggregateRoot> getById(id: String, type: Class<T>): T {
        /*
         * Get the events from the event store
         */
        val response = eventStore.getEvents("$id_$type")
        when (response) {
            is GetEventsResponse.Success -> {
                //we are sure that only one aggregate will be returned
                return buildAggregateFromHistory(type, response.aggregates[0].events, id, response.aggregates.first().snapshot)

            }
            is GetEventsResponse.AggregateNotFound -> {
                throw AggregateNotFoundException(id)
            }
            else -> throw IllegalStateException("unknown state")
        }
    }
```
Which would just throw not found. The thing is that we would not know for which Aggregate type the wrongly provided id is and we would wonder if the searched Aggregate really is missing or we are providing a wrong aggregate id (for another aggregate).

I think a better solution would be to add the class type to the EventStore's methods 
```Kotlin
    fun getEvents(aggregateId: String): GetEventsResponse

    fun getEvents(aggregateIds: List<String>): GetEventsResponse
```
We would also add the already existing aggregateTypeProperty (which currently is only stored in the Event entity) to the EventSnapshot entity. This way when we search for an aggregate we would be able to do something like: 

```Kotlin
override fun getEvents(aggregateId: String, aggregateType: String): GetEventsResponse {
        val dataStore = DatastoreServiceFactory.getDatastoreService()

        val snapshotKey = KeyFactory.createKey(snapshotKind, aggregateId)
        val snapshotEntity = try {
            dataStore.get(snapshotKey)
        } catch (ex: EntityNotFoundException) {
            return GetEventsResponse.SnapshotNotFound
        }
        //new
        val storedAggregateType = snapshotEntity.getProperty(aggregateTypeProperty)
        if (storedAggregateType != aggregateType) {
            throw Exception("Was searching for $aggregateType but provided id for $storedAggregateType")
        }
        ......
```
This way we would be able to know exactly for what the id we provided was and it would be easier for debugging.

**Comment by VasilMitovClouway** [comment]
Now that i think of it it would be better to not throw exception but to add new GetEventsResponse which would be better handled by the HttpEventStore.

**Comment by VasilMitovClouway** [comment]
I have implemented both my idea and the idea suggested by @mgenov
